<?php
/**
 * Created by PhpStorm.
 * User: Трик
 * Date: 10.07.2016
 * Time: 11:30
 */

require_once "global_class.php";

class AdmMessage extends GlobalClass
{
    public function __construct($db)
    {
        parent::__construct("message", $db);
    }

    public function addMessage($new_values)
    {
        return $this->add($new_values); // TODO: Change the autogenerated stub
    }

    public function editMessage($id, $title, $desc, $short_desc, $type) {
        return $this->edit($id, array("title" => $title, "description" => $desc, "short_desc" => $short_desc, "type" => $type));
    }

    public function deleteMessage($id)
    {
        return $this->delete($id); // TODO: Change the autogenerated stub
    }

    public function getLast() {
        return $this->getLastIDIn();
    }
}